[UPDATE] System.Reactive to 4.1.5 WIP
STARIONGROUP/COMET-SDK-Community-Edition pull request #236
Opened 2022-05-20 09:56 UTC by lxatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-SDK-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-SDK-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
[UPDATE] System.Reactive to 4.1.5

2022-05-20 11:36 UTC, samatrhea requested changes

2022-05-20 11:36 UTC, samatrhea commented on CDP4Dal/CDP4Dal.csproj
> +      [Update] .Net Framework to System.Reactive 4.1.5
please rephrase to 
[Update] System.Reactive to version 4.1.5
[Drop] support for net45;net451;net452

2022-05-20 11:36 UTC, samatrhea commented on CDP4Common/CDP4Common.csproj
> +    <TargetFrameworks>net46;net461;net462;net47;net471;net472;net48;netstandard2.0;netstandard2.1;netcoreapp3.1</TargetFrameworks>
please add to the PackageReleaseNotes:

[Drop] support for net45;net451;net452

2022-05-20 11:36 UTC, samatrhea commented on CDP4Dal/CDP4Dal.csproj
> -    <PackageReference Include="Rx-Core" version="2.2.5" />
nice that these can be dropped!

2022-05-20 11:36 UTC, samatrhea commented on CDP4JsonFileDal/CDP4JsonFileDal.csproj
> +    <TargetFrameworks>net46;net461;net462;net47;net471;net472;net48;netstandard2.0;netstandard2.1;netcoreapp3.1</TargetFrameworks>
please add to the PackageReleaseNotes:

[Drop] support for net45;net451;net452

2022-05-20 11:36 UTC, samatrhea commented on CDP4JsonSerializer/CDP4JsonSerializer.csproj
> +    <TargetFrameworks>net46;net461;net462;net47;net471;net472;net48;netstandard2.0;netstandard2.1;netcoreapp3.1</TargetFrameworks>
please add to the PackageReleaseNotes:

[Drop] support for net45;net451;net452

2022-05-20 11:36 UTC, samatrhea commented on CDP4RequirementsVerification/CDP4RequirementsVerification.csproj
> +    <TargetFrameworks>net46;net461;net462;net47;net471;net472;net48;netstandard2.0;netstandard2.1;netcoreapp3.1</TargetFrameworks>
please add to the PackageReleaseNotes:

[Drop] support for net45;net451;net452

2022-05-20 11:36 UTC, samatrhea commented on CDP4Rules/CDP4Rules.csproj
> +    <TargetFrameworks>net46;net461;net462;net47;net471;net472;net48;netstandard2.0;netstandard2.1;netcoreapp3.1</TargetFrameworks>
please add to the PackageReleaseNotes:

[Drop] support for net45;net451;net452

2022-05-20 11:36 UTC, samatrhea commented on CDP4ServicesDal/CDP4ServicesDal.csproj
> +    <TargetFrameworks>net46;net461;net462;net47;net471;net472;net48;netstandard2.0;netstandard2.1;netcoreapp3.1</TargetFrameworks>
please add to the PackageReleaseNotes:

[Drop] support for net45;net451;net452

2022-05-20 11:36 UTC, samatrhea commented on CDP4WspDal/CDP4WspDal.csproj
> +    <TargetFrameworks>net46;net461;net462;net47;net471;net472;net48;netstandard2.0;netstandard2.1;netcoreapp3.1</TargetFrameworks>
please add to the PackageReleaseNotes:

[Drop] support for net45;net451;net452

2022-05-30 08:57 UTC, samatrhea approved these changes

2024-08-14 14:36 UTC, samatstariongroup commented
in the meantime updated to 6.0.1

2024-08-14 14:36 UTC, closed without merging