Fix #262: Moved from Newtonsoft.Json to System.Text.Json
STARIONGROUP/COMET-SDK-Community-Edition pull request #324
Opened 2024-03-21 13:43 UTC by antoineatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-SDK-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-SDK-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

Fix #262 
- Remove all dependencies to Newtonsoft.Json 
- All (de)serializers uses the most low-level Json calls
- Creation of CDP4DalJsonSerializer that support (de)serialization of any PostOperation class

2024-03-21 15:43 UTC, antoineatrhea commented
I think that the issue found by SQ should be discarded and non-relevant with the context of the code

2024-03-22 11:12 UTC, samatrhea requested changes

2024-03-22 11:12 UTC, samatrhea commented on versionBump.sh
> +#!/bin/bash
make sure to add some docs somewhere what the purpose is and how to use it

2024-03-22 13:48 UTC, samatrhea requested changes

2024-03-22 13:48 UTC, samatrhea commented on CDP4DalJsonSerializer/JsonConverter/PostOperationJsonConverter.cs
> +        public PostOperationJsonConverter(bool ignoreCopyProperty = false)
the default should be true, since this is special for COMET and not supported by version 1,0.0 of 10-25

2024-12-04 11:08 UTC, closed without merging